/**
 * Sitemap Index
 *
 * References all sitemaps for the site.
 * Google recommends using a sitemap index when you have multiple sitemaps.
 * https://developers.google.com/search/docs/crawling-indexing/sitemaps/large-sitemaps
 */

import type { APIRoute } from "astro";

const SITE_URL = "https://monsoftsolutions.com";

export const GET: APIRoute = async () => {
  const lastmod = new Date().toISOString().split("T")[0];

  const xml = `<?xml version="1.0" encoding="UTF-8"?>
<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <!-- Main sitemap (pages, services) - generated by Astro -->
  <sitemap>
    <loc>${SITE_URL}/sitemap-0.xml</loc>
    <lastmod>${lastmod}</lastmod>
  </sitemap>
  
  <!-- Blog sitemap with images -->
  <sitemap>
    <loc>${SITE_URL}/blog-sitemap.xml</loc>
    <lastmod>${lastmod}</lastmod>
  </sitemap>
</sitemapindex>`;

  return new Response(xml, {
    headers: {
      "Content-Type": "application/xml",
      "Cache-Control": "public, max-age=3600",
    },
  });
};
